//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteConsoleApp.VendedorPassagemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passagem", Namespace="http://schemas.datacontract.org/2004/07/PassagemServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Passagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponivel {
            get {
                return this.DisponivelField;
            }
            set {
                if ((this.DisponivelField.Equals(value) != true)) {
                    this.DisponivelField = value;
                    this.RaisePropertyChanged("Disponivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmptyQueueException", Namespace="http://schemas.datacontract.org/2004/07/VendedorPassagem.Exception")]
    [System.SerializableAttribute()]
    public partial class EmptyQueueException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendedorPassagemService.IVendedorPassagemService")]
    public interface IVendedorPassagemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendedorPassagemService/ComprarPassagem", ReplyAction="http://tempuri.org/IVendedorPassagemService/ComprarPassagemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClienteConsoleApp.VendedorPassagemService.EmptyQueueException), Action="http://tempuri.org/IVendedorPassagemService/ComprarPassagemEmptyQueueExceptionFau" +
            "lt", Name="EmptyQueueException", Namespace="http://schemas.datacontract.org/2004/07/VendedorPassagem.Exception")]
        ClienteConsoleApp.VendedorPassagemService.Passagem ComprarPassagem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendedorPassagemService/ComprarPassagem", ReplyAction="http://tempuri.org/IVendedorPassagemService/ComprarPassagemResponse")]
        System.Threading.Tasks.Task<ClienteConsoleApp.VendedorPassagemService.Passagem> ComprarPassagemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendedorPassagemService/ListarPassagens", ReplyAction="http://tempuri.org/IVendedorPassagemService/ListarPassagensResponse")]
        ClienteConsoleApp.VendedorPassagemService.Passagem[] ListarPassagens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendedorPassagemService/ListarPassagens", ReplyAction="http://tempuri.org/IVendedorPassagemService/ListarPassagensResponse")]
        System.Threading.Tasks.Task<ClienteConsoleApp.VendedorPassagemService.Passagem[]> ListarPassagensAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendedorPassagemServiceChannel : ClienteConsoleApp.VendedorPassagemService.IVendedorPassagemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendedorPassagemServiceClient : System.ServiceModel.ClientBase<ClienteConsoleApp.VendedorPassagemService.IVendedorPassagemService>, ClienteConsoleApp.VendedorPassagemService.IVendedorPassagemService {
        
        public VendedorPassagemServiceClient() {
        }
        
        public VendedorPassagemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendedorPassagemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedorPassagemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedorPassagemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteConsoleApp.VendedorPassagemService.Passagem ComprarPassagem() {
            return base.Channel.ComprarPassagem();
        }
        
        public System.Threading.Tasks.Task<ClienteConsoleApp.VendedorPassagemService.Passagem> ComprarPassagemAsync() {
            return base.Channel.ComprarPassagemAsync();
        }
        
        public ClienteConsoleApp.VendedorPassagemService.Passagem[] ListarPassagens() {
            return base.Channel.ListarPassagens();
        }
        
        public System.Threading.Tasks.Task<ClienteConsoleApp.VendedorPassagemService.Passagem[]> ListarPassagensAsync() {
            return base.Channel.ListarPassagensAsync();
        }
    }
}
